### PR TITLE
fast auc in validatioin plot

### PR DESCRIPTION
**Pull request by tonglu**

### CODE REVIEW

**Comment by tonglu** [comment]
@eddieyue does this still provide the CI estimation for the AUC statistic?

**Comment by robertzk** [comment]
Please fix CI.

**Comment by eddieyue** [comment]
@tonglu don't think it support the CI estimation for AUC statistics, tried to figure it out once.

**Comment by tonglu** [comment]
@eddieyue then it is not a replacement as it takes away the CI estimation functionality.

**Pull request closed without merging**
